### ISSUE TITLE
gfeeds doesn't start after latest update

### ISSUE THREAD

**Issue by Xathros1** [flathub/org.gabmus.gfeeds#8]
Terminal output:

```
cb@tumbleweed-pc:~> flatpak run org.gabmus.gfeeds
Time localization unavailable for locale `en_US`
Traceback (most recent call last):
  File "/app/bin/gfeeds", line 74, in <module>
    from gfeeds import __main__
  File "/app/lib/python3.9/site-packages/gfeeds/__main__.py", line 8, in <module>
    from gfeeds.app_window import GFeedsAppWindow
  File "/app/lib/python3.9/site-packages/gfeeds/app_window.py", line 1, in <module>
    from gfeeds.main_leaflet import MainLeaflet
  File "/app/lib/python3.9/site-packages/gfeeds/main_leaflet.py", line 11, in <module>
    from gfeeds.webview import GFeedsWebView
  File "/app/lib/python3.9/site-packages/gfeeds/webview.py", line 4, in <module>
    from gfeeds.build_reader_html import build_reader_html
  File "/app/lib/python3.9/site-packages/gfeeds/build_reader_html.py", line 2, in <module>
    from gfeeds.readability_wrapper import RDoc
  File "/app/lib/python3.9/site-packages/gfeeds/readability_wrapper.py", line 3, in <module>
    from readability.readability import *
  File "/app/lib/python3.9/site-packages/readability/__init__.py", line 3, in <module>
    from .readability import Document
  File "/app/lib/python3.9/site-packages/readability/readability.py", line 7, in <module>
    from lxml.etree import tounicode
ModuleNotFoundError: No module named 'lxml'

```

**Comment by neildarlow** [comment]
Please check the required dependencies carefully. XML has been added but now Pygments is missing. There may be others!

**Comment by GabMus** [comment]
I made the mistake of trusting the output of flatpak-generator-pip. I'm on it, sorry for the inconvenience.

By the way, please report issues on the upstream gitlab repo, I don't look at github often.

**Comment by neildarlow** [comment]
Sure, no problem. I reported at the flathub github repository because I thought this was a simple flathub packaging issue not an upstream one.

**Comment by Xathros1** [comment]
https://gitlab.gnome.org/World/gfeeds/-/issues/95
